#!/usr/bin/env bash

# Step 1: Test Locally on Windows 11
echo "📋 STEP 1: LOCAL TESTING (Windows 11)"
echo "=================================="
echo ""
echo "1. Copy environment template:"
echo "   cp .env.docker .env"
echo ""
echo "2. Edit .env file with your values:"
echo "   - Update MYSQL passwords"
echo "   - Update JWT_SECRET"
echo "   - Update EMAIL credentials"
echo ""
echo "3. Start containers:"
echo "   docker-compose up --build"
echo ""
echo "4. Test in browser:"
echo "   Frontend: http://localhost:3000"
echo "   Backend:  http://localhost:5000/api"
echo ""
echo "5. View logs:"
echo "   docker-compose logs -f"
echo ""

# Step 2: Push to GitHub
echo ""
echo "📋 STEP 2: PUSH TO GITHUB"
echo "=================================="
echo ""
echo "1. Add all files:"
echo "   git add ."
echo ""
echo "2. Commit:"
echo "   git commit -m 'feat: add Docker setup for Azure deployment'"
echo ""
echo "3. Push:"
echo "   git push origin main"
echo ""

# Step 3: Azure Setup
echo ""
echo "📋 STEP 3: AZURE VM SETUP"
echo "=================================="
echo ""
echo "1. Create Azure VM:"
echo "   - Resource: Virtual Machine"
echo "   - OS: Ubuntu 22.04 LTS"
echo "   - Size: Standard_B2s (minimum)"
echo "   - Auth: SSH key"
echo ""
echo "2. Note the public IP address"
echo ""
echo "3. SSH into VM:"
echo "   ssh azureuser@YOUR_PUBLIC_IP"
echo ""
echo "4. Run setup script:"
echo "   git clone git@github.com:YOUR_USERNAME/HealthCare.git ~/healthcare"
echo "   cd ~/healthcare"
echo "   chmod +x azure-setup.sh"
echo "   ./azure-setup.sh"
echo ""

# Step 4: GitHub Actions
echo ""
echo "📋 STEP 4: GITHUB ACTIONS CI/CD"
echo "=================================="
echo ""
echo "1. Add GitHub Secrets:"
echo "   Settings → Secrets and variables → Actions"
echo ""
echo "2. Create these secrets:"
echo "   - AZURE_VM_IP: Your VM public IP"
echo "   - AZURE_VM_USERNAME: azureuser"
echo "   - AZURE_VM_SSH_KEY: Your SSH private key contents"
echo ""
echo "3. Now every push to 'main' will auto-deploy!"
echo ""

# Step 5: Verify Deployment
echo ""
echo "📋 STEP 5: VERIFY DEPLOYMENT"
echo "=================================="
echo ""
echo "1. SSH to Azure VM:"
echo "   ssh azureuser@YOUR_PUBLIC_IP"
echo ""
echo "2. Check containers:"
echo "   docker-compose ps"
echo ""
echo "3. View logs:"
echo "   docker-compose logs -f"
echo ""
echo "4. Access application:"
echo "   Frontend: http://YOUR_PUBLIC_IP:3000"
echo "   Backend:  http://YOUR_PUBLIC_IP:5000/api"
echo ""

# Step 6: Production Setup
echo ""
echo "📋 STEP 6: PRODUCTION HARDENING (Optional)"
echo "=================================="
echo ""
echo "1. Install SSL certificate:"
echo "   ssh azureuser@YOUR_PUBLIC_IP"
echo "   sudo apt-get install -y certbot python3-certbot-nginx"
echo "   sudo certbot certonly --standalone -d your-domain.com"
echo ""
echo "2. Configure Nginx reverse proxy:"
echo "   sudo apt-get install -y nginx"
echo "   sudo nano /etc/nginx/sites-available/healthcare"
echo "   # Copy content from nginx.conf"
echo "   sudo ln -s /etc/nginx/sites-available/healthcare /etc/nginx/sites-enabled/"
echo "   sudo nginx -t"
echo "   sudo systemctl restart nginx"
echo ""
echo "3. Update DNS to point to Azure VM IP"
echo ""
echo "4. Update .env with HTTPS URLs"
echo ""

# Summary
echo ""
echo "=================================="
echo "✅ DEPLOYMENT CHECKLIST"
echo "=================================="
echo ""
echo "Local (Windows 11):"
echo "  [ ] Docker Desktop installed"
echo "  [ ] Containers tested locally"
echo "  [ ] Changes pushed to GitHub"
echo ""
echo "Azure VM (Ubuntu):"
echo "  [ ] VM created"
echo "  [ ] SSH access working"
echo "  [ ] Containers running"
echo "  [ ] Database migrations completed"
echo ""
echo "GitHub Actions:"
echo "  [ ] Secrets configured"
echo "  [ ] Workflow file present"
echo "  [ ] CI/CD triggered on push"
echo ""
echo "Production (Optional):"
echo "  [ ] SSL/TLS configured"
echo "  [ ] Nginx reverse proxy setup"
echo "  [ ] DNS records updated"
echo "  [ ] Monitoring enabled"
echo ""

echo ""
echo "📚 DOCUMENTATION:"
echo "  • README_DOCKER_SETUP.md - Overview & getting started"
echo "  • DOCKER_SETUP_COMPLETE.md - What was created"
echo "  • AZURE_DEPLOYMENT_GUIDE.md - Detailed step-by-step"
echo "  • DOCKER_QUICKREF.md - Common commands"
echo ""

echo "🚀 READY TO DEPLOY!"
echo ""
